[versions]
accompanist-swiperefresh = "0.36.0"
agp = "8.10.0"
aws-android-sdk-s3 = "2.22.0"
burnoutcrew-reorderable = "0.9.6"
guava = "33.2.1-android"
kotlin = "2.2.20"
kotlinx-serialization = "1.7.3"
ksp = "2.2.20-2.0.4"
google-service = "4.4.4"

compose-bom = "2025.08.00"
core-ktx = "1.17.0"
activity-compose = "1.11.0"
lifecycle = "2.9.4"
navigation = "2.9.4"

coroutines = "1.10.2"
room = "2.8.1"
dagger = "2.57.2"
lottie = "6.7.1"
accompanist = "0.34.0"
firebase-bom = "34.6.0"
junit = "4.13.2"
junit-version = "1.3.0"
espresso-core = "3.7.0"
amazon = "2.81.1"
amazon-sdk = "1.12.767"
appcompat = "1.7.1"
material = "1.13.0"
play-services-auth = "21.2.0"
coil = "2.6.0"
work = "2.9.1"


[libraries]
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist-swiperefresh" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
aws-android-sdk-s3-v2220 = { module = "com.amazonaws:aws-android-sdk-s3", version.ref = "aws-android-sdk-s3" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material = { module = "androidx.compose.material:material" }

composereorderable-reorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "burnoutcrew-reorderable" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }

amazon-s3 = { module = "com.amazonaws:aws-android-sdk-s3", version.ref = "amazon"}
aws-java-sdk-s3 = { module = "com.amazonaws:aws-java-sdk-s3", version.ref = "amazon-sdk" }

lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "play-services-auth" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }

[bundles]
compose-base = [
    "androidx-core-ktx",
    "androidx-activity-compose",
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-runtime-compose",
    "compose-ui",
    "compose-foundation",
    "compose-material3",
    "compose-ui-tooling-preview",
]

coroutines = [
    "coroutines-core",
    "coroutines-android",
]

room = [
    "room-runtime",
    "room-ktx",
]

firebase = [
    "firebase-auth",
    "firebase-firestore",
    "firebase-storage",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
firebase = { id = "com.google.gms.google-services", version.ref = "google-service"}
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }  # <-- НОВОЕ